name: Sync Files with Google Drive

on:
  push:
    branches:
      - gpt-2  # Adjust to your desired branch

jobs:
  sync_to_drive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}

    - name: Install gdrive CLI
      run: |
        # Ensure wget is installed and update system
        sudo apt-get update -y
        sudo apt-get install wget -y
        sudo apt-get install unzip -y  # Install unzip in case we use zip files
        sudo apt-get install golang-go -y  # Install Go to build gdrive from source

        # Clear previous installations of gdrive (just in case)
        sudo rm -f /usr/local/bin/gdrive

        # Download the tar.gz release of gdrive from the GitHub releases page
        wget https://github.com/prasmussen/gdrive/archive/refs/tags/2.1.0.tar.gz -O /tmp/gdrive-linux-x64.tar.gz

        # Extract the tar.gz file
        tar -xzvf /tmp/gdrive-linux-x64.tar.gz -C /tmp

        # Navigate to the extracted folder
        cd /tmp/gdrive-2.1.0

        # Initialize the Go module
        go mod init github.com/prasmussen/gdrive

        # Add a replace directive to fix the dependency issue
        echo 'replace github.com/sabhiram/go-git-ignore => github.com/sabhiram/go-git-ignore v0.0.0-20210923224102-525f6e181f06' >> go.mod


        # Tidy up dependencies (fetch required modules)
        go mod tidy

        # Build the binary
        go build -o /usr/local/bin/gdrive gdrive.go

        # Verify the gdrive installation
        gdrive version

    - name: Move data folder to temporary location
      run: |
        mv data /tmp/data_backup

    - name: Upload to Google Drive
      run: |
        gdrive upload --recursive . --folder ${{ secrets.GDRIVE_FOLDER_ID }}

    - name: Move data folder back
      run: |
        mv /tmp/data_backup data
