name: Sync to Google Drive

on:
  push:
    branches:
      - gpt-2

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONFIG }}' > ~/.config/rclone/rclone.conf
          
      - name: Check Google Drive paths
        run: |
          echo "Root contents:"
          rclone lsd gdrive:
          echo "\nMyDrive contents:"
          rclone lsd "gdrive:MyDrive"
          echo "\nColab Notebooks contents:"
          rclone lsd "gdrive:MyDrive/Colab Notebooks"
          echo "\nTarget folder contents:"
          rclone ls "gdrive:MyDrive/Colab Notebooks/darkly_speaking_dexter"
          
      - name: Sync files to Google Drive
        run: |
          pwd
          ls -la
          echo "Starting sync..."
          rclone sync . "gdrive:MyDrive/Colab Notebooks/darkly_speaking_dexter" -v --exclude=.git/** --refresh-times