name: Sync to Google Drive

on:
  push:
    branches:
      - gpt-2

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # This is crucial - it gets your actual branch files
        uses: actions/checkout@v3
        
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONFIG }}' > ~/.config/rclone/rclone.conf
          
      - name: Sync files to Google Drive
        run: |
          pwd
          ls -la  # Let's see what files we actually have
          echo "Starting sync..."
          rclone sync . "gdrive:MyDrive/Colab Notebooks/darkly_speaking_dexter" -v --exclude=.git/**