name: Sync to Google Drive

on:
  push:
    branches:
      - gpt-2

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONFIG }}' > ~/.config/rclone/rclone.conf
          
      - name: Debug checks
        run: |
          echo "Testing Google Drive access..."
          rclone lsd gdrive:
          echo "\nTesting target folder..."
          rclone mkdir "gdrive:MyDrive/Colab Notebooks/dex"
          echo "\nListing current directory..."
          ls -la
          echo "\nTrying to copy a single file..."
          rclone copyto readme.md "gdrive:MyDrive/Colab Notebooks/dex/readme.md" -v
          
      - name: Force sync to Google Drive
        run: |
          rclone sync . "gdrive:MyDrive/Colab Notebooks/dex" \
            -v \
            --ignore-existing \
            --ignore-times \
            --no-update-modtime \
            --checksum \
            --verbose \
            --transfers=1 \
            -P