name: Sync to Google Drive

on:
  push:
    branches:
      - gpt-2

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONFIG }}' > ~/.config/rclone/rclone.conf
          
      - name: Aggressive sync to Google Drive
        run: |
          rclone sync . "gdrive:MyDrive/Colab Notebooks/darkly_speaking_dexter" \
            -v \
            --exclude=.git/** \
            --refresh-times \
            --checksum \
            --update \
            --create-empty-src-dirs \
            --track-renames \
            --fast-list \
            --transfers=32 \
            --checkers=32 \
            --drive-chunk-size=32M \
            --drive-acknowledge-abuse \
            --drive-allow-import-name-change \
            --ignore-size \
            -P