name: Sync Files with Google Drive

on:
  push:
    branches:
      - gpt-2  # You can adjust this to your desired branches

jobs:
  sync_to_drive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}

    - name: Install gdrive CLI
      run: |
        # Ensure wget is installed and try downloading the binary
        sudo apt-get update -y
        sudo apt-get install wget -y

        # Clear any previous installations of gdrive (just in case)
        sudo rm -f /usr/local/bin/gdrive

        # Download gdrive CLI tool
        wget -v https://github.com/prasmussen/gdrive/releases/download/2.1.0/gdrive-linux-x64 -O /tmp/gdrive-linux-x64
        if [ ! -f /tmp/gdrive-linux-x64 ]; then
          echo "Download failed"
          exit 1
        fi

        # Make it executable
        chmod +x /tmp/gdrive-linux-x64
        
        # Move to local bin directory
        sudo mv /tmp/gdrive-linux-x64 /usr/local/bin/gdrive
        
        # Verify the gdrive installation
        gdrive version

    - name: Move data folder to temporary location
      run: |
        mv data /tmp/data_backup

    - name: Upload to Google Drive
      run: |
        gdrive upload --recursive . --folder ${{ secrets.GDRIVE_FOLDER_ID }}

    - name: Move data folder back
      run: |
        mv /tmp/data_backup data
