name: Test Google Drive Connection

on:
  push:
    branches:
      - gpt-2

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONFIG }}' > ~/.config/rclone/rclone.conf
          cat ~/.config/rclone/rclone.conf  # This will help us see what's actually in the config
          
      - name: Test Drive connection
        run: |
          rclone lsd gdrive: