name: Test Google Drive Connection

on:
  push:
    branches:
      - gpt-2

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          # Write config with explicit newlines
          cat > ~/.config/rclone/rclone.conf << 'EOL'
            ${{ secrets.RCLONE_CONFIG }}
          EOL
          # Check config format
          echo "Config file contents:"
          cat ~/.config/rclone/rclone.conf
          echo "Config file permissions:"
          ls -l ~/.config/rclone/rclone.conf
          
      - name: Test Drive connection
        run: |
          echo "Testing rclone version:"
          rclone version
          echo "Testing drive connection:"
          rclone listremotes
          echo "Testing drive listing:"
          rclone lsd gdrive: