name: Sync to Google Drive

on:
  push:
    branches:
      - gpt-2

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONFIG }}' > ~/.config/rclone/rclone.conf
          
      - name: Test Drive listing
        run: |
          rclone lsd gdrive:
          
      - name: Sync files to Google Drive
        run: |
          rclone sync . "gdrive:MyDrive/Colab Notebooks/darkly_speaking_dexter"