name: Sync Files with Google Drive

on:
  push:
    branches:
      - gpt-2  # You can adjust this to your desired branches

jobs:
  sync_to_drive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}

    - name: Install gdrive CLI
      run: |
        # Download and install gdrive (CLI tool for Google Drive)
        wget -q https://github.com/prasmussen/gdrive/releases/download/2.1.0/gdrive-linux-x64
        chmod +x gdrive-linux-x64
        sudo mv gdrive-linux-x64 /usr/local/bin/gdrive

    - name: Move data folder to temporary location
      run: |
        mv data /tmp/data_backup

    - name: Upload to Google Drive
      run: |
        gdrive upload --recursive . --folder ${{ secrets.GDRIVE_FOLDER_ID }}

    - name: Move data folder back
      run: |
        mv /tmp/data_backup data
